project_id = "drproject-gcp-aws"
vpc_name = "prod-vpc"
subnet_names = ["public", "private-subnet"]
cidr_ranges = ["10.0.0.0/24","10.0.1.0/24"]
bucket_name = "furniture-log"
region = "us-central1"
bucket_class = "STANDARD"
router_name = "prod-router"
nat_name = "prod-nat"
zone = "us-central1-b"
vm_name = "private-vm"
machine_type = "n1-standard-1"
vm_image = "debian-cloud/debian-11"
master_ipv4_cidr_block = "172.16.0.0/28"
nodepool_name = "node-pool"
cluster_name = "privatecluster"
workern_type = "e2-micro"
workern_disktype = "pd-standard"
workern_disksize = 50
workern_imagetype = "ubuntu_containerd"
workern_oauthscopes = ["https://www.googleapis.com/auth/cloud-platform"]
accounts = ["gke-sa", "instance-sa"]
roles = ["roles/storage.objectViewer", "roles/container.admin"]