pipeline {
    agent any
    environment {
        AWS_REGION = 'us-west-2' // Adjust based on your setup
        //TERRAFORM_WORKSPACE = 'prod'
        TERRAFORM_DIR = './Ishaque/infrastructure-automation/environments/production'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ishaque-a-jaleel/DevOps-POC.git'
            }
        }
        
        //stage('Fetch Secrets') {
        //    steps {
        //        script {
        //            // Using AWS CLI to retrieve secrets and export them as environment variables
        //            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'your-aws-credentials']]) {
        //                sh """
        //                export TF_VAR_db_password=$(aws secretsmanager get-secret-value --secret-id my-db-secret --query SecretString --output text --region ${AWS_REGION} | jq -r .password)
        //                export TF_VAR_api_key=$(aws secretsmanager get-secret-value --secret-id my-api-secret --query SecretString --output text --region ${AWS_REGION} | jq -r .api_key)
        //                """
        //            }
        //        }
        //    }
        //}
        
        stage('Terraform Init') {
            steps {
                sh 'terraform -chdir=${TERRAFORM_DIR} init'
            }
        }
        
        stage('Terraform Plan') {
            steps {
                sh 'terraform -chdir=${TERRAFORM_DIR} plan -out=tfplan'
            }
        }
        
        stage('Approval') {
            steps {
                input message: "Apply the Terraform plan?", ok: "Proceed"
            }
        }
        
        stage('Terraform Apply') {
            steps {
                sh 'terraform -chdir=${TERRAFORM_DIR} apply tfplan'
            }
        }
    }
}
