vpc_name                    = "production-vpc"
cidr_block                  = "10.0.0.0/16"
enable_dns_support          = "true"
environment                 = "prod"
public_subnet_count         = 2
private_subnet_count        = 2
public_subnets_cidr_blocks  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets_cidr_blocks = ["10.0.3.0/24", "10.0.4.0/24"]
azs                         = ["us-east-1a", "us-east-1b"]
map_public_ip_on_launch     = "true"
igw_name                    = "prod-igw"
nat_name                    = "prod-nat"
pub_rt_name                 = "prod-public-rt"
prvt_rt_name                = "prod-private-rt"
ami_id                      = "ami-00f251754ac5da7f0"
instance_type               = "t2.nano"
domain_name                 = "dopeops.cloud"
key_name                    = "prod-bastion-key"
bastion_public_key          = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHEVx/vVXrSamPAqnvbvRKOwD6rYXZT3wBfKUyYsGjgI ishaque.abdul@urolime.com"
tg_name                     = "prod-mealie-tg"
ecs_cluster_name            = "prod-mealie-cluster"
task_def_name               = "prod-mealie-app"
task_cpu                    = 1024
task_mem                    = 2048
task_def_ecr_repository_url = "ghcr.io/mealie-recipes/mealie:v2.0.0"
ecs_svc_name                = "prod-mealie-app"
ecs_desired_count           = 1
task_container_port         = 9000
task_host_port              = 9000
ecs_max_count               = 200
ecs_min_count               = 100
#task_container_port         = 80
#task_host_port              = 80
